export const Images = {
  logo: "/images/logo.webp",
  blogStudioLogo: "/images/blog-studio-logo.png",
  socialStudioLogo: "/images/social-studio-logo.png",
  bsPreview: "/images/bs-preview.png",
  ssPreview: "/images/ss-preview.png",
  og: "/images/og.png",
  devLogo: "/images/platforms/dev-logo.webp",
  mediumLogo: "/images/platforms/medium-logo.webp",
  hashnodeLogo: "/images/platforms/hashnode-logo.webp",
  ghostLogo: "/images/platforms/ghost-logo.webp",
  wordpressLogo: "/images/platforms/wordpress-logo.webp",
  bloggerLogo: "/images/platforms/blogger-logo.webp",
  linkedinLogo: "/images/platforms/linkedin-logo.webp",
  threadsLogo: "/images/platforms/threads-logo.png",
  bskyLogo: "/images/platforms/bsky-logo.jpeg",
  fbLogo: "/images/platforms/facebook-logo.webp",
  instagramLogo: "/images/platforms/instagram-logo.webp",
  xLogo: "/images/platforms/x-logo.jpeg",
};
